-- Script to populate marketplace with sample avatars
-- Run this in your Supabase SQL Editor after the main schema

-- Insert sample marketplace avatars
INSERT INTO public.avatars (
  name, description, image_url, price, rating, total_sales, creator, mbti,
  personality, favorites, grow_up_story, voice_description, languages,
  lifestyle, gallery_images, category, is_public, user_id
) VALUES
(
  'Oliver',
  'A joyful young avatar perfect for family content and educational interactions',
  '/lovable-uploads/bbe9701d-0f56-426e-8fff-fc196bea0815.png',
  89.99,
  4.9,
  342,
  'KidsStudio',
  'ENFP',
  ARRAY['Cheerful', 'Curious', 'Energetic', 'Playful'],
  ARRAY['Building blocks', 'Storytelling', 'Adventure games', 'Ice cream'],
  'Oliver grew up in a cozy suburban neighborhood where imagination was his best friend. He spent countless hours building fantastic worlds with his toys and sharing wild stories with anyone who would listen.',
  'Bright, enthusiastic child voice with infectious laughter',
  ARRAY['English', 'Spanish'],
  ARRAY['Family-friendly', 'Educational', 'Creative play'],
  ARRAY['/lovable-uploads/bbe9701d-0f56-426e-8fff-fc196bea0815.png'],
  'Kids',
  true,
  NULL -- Will be system-owned for marketplace
),
(
  'Emma',
  'A sophisticated professional avatar ideal for corporate presentations and business communications',
  '/lovable-uploads/621420e1-be52-41a0-a02b-9fa64b7a52f7.png',
  129.99,
  4.8,
  287,
  'ProStudio',
  'INTJ',
  ARRAY['Professional', 'Analytical', 'Confident', 'Detail-oriented'],
  ARRAY['Coffee', 'Strategic planning', 'Tech innovations', 'Minimalist design'],
  'Emma climbed the corporate ladder through dedication and smart decision-making. She believes in efficiency and always looks for innovative solutions to complex problems.',
  'Clear, professional tone with authoritative presence',
  ARRAY['English', 'German', 'French'],
  ARRAY['Business', 'Corporate', 'Leadership'],
  ARRAY['/lovable-uploads/621420e1-be52-41a0-a02b-9fa64b7a52f7.png'],
  'Business',
  true,
  NULL
),
(
  'Aria',
  'A free-spirited avatar perfect for travel vlogs and nature content',
  '/lovable-uploads/ba97f001-ee2b-43d0-b1b7-2ae06d422f96.png',
  149.99,
  4.9,
  456,
  'NatureStudio',
  'ISFP',
  ARRAY['Free-spirited', 'Artistic', 'Nature-loving', 'Adventurous'],
  ARRAY['Hiking', 'Photography', 'Sunset watching', 'Organic food'],
  'Aria grew up in a small mountain town, always feeling most at home in nature. She discovered her love for photography while exploring hidden trails and capturing the beauty of untouched landscapes.',
  'Gentle, melodic voice with a hint of wanderlust',
  ARRAY['English', 'Japanese', 'Korean'],
  ARRAY['Travel', 'Nature', 'Photography', 'Wellness'],
  ARRAY['/lovable-uploads/ba97f001-ee2b-43d0-b1b7-2ae06d422f96.png'],
  'Lifestyle',
  true,
  NULL
),
(
  'Marcus',
  'A tech-savvy avatar perfect for programming tutorials and tech content',
  '/lovable-uploads/7b694883-4403-4c7c-9361-01ac8871d1bc.png',
  199.99,
  4.7,
  198,
  'TechStudio',
  'ENTP',
  ARRAY['Innovative', 'Analytical', 'Tech-savvy', 'Problem-solver'],
  ARRAY['Coding', 'AI research', 'Gaming', 'Tech gadgets'],
  'Marcus started coding at age 10 and has been passionate about technology ever since. He believes in using AI to solve real-world problems and make life better for everyone.',
  'Confident, clear voice with technical precision',
  ARRAY['English', 'Python', 'JavaScript'],
  ARRAY['Technology', 'Innovation', 'Programming'],
  ARRAY['/lovable-uploads/7b694883-4403-4c7c-9361-01ac8871d1bc.png'],
  'Technology',
  true,
  NULL
),
(
  'Luna',
  'An artistic avatar perfect for creative content and artistic inspiration',
  '/lovable-uploads/3da4a6b0-da99-437a-8673-fcf40dadcace.png',
  159.99,
  4.8,
  324,
  'ArtStudio',
  'INFP',
  ARRAY['Creative', 'Dreamy', 'Artistic', 'Empathetic'],
  ARRAY['Painting', 'Poetry', 'Moon gazing', 'Vintage books'],
  'Luna has always been drawn to the mystical and beautiful. She spends her nights painting under moonlight and writing poetry that captures the essence of dreams and emotions.',
  'Soft, dreamy voice with artistic flair',
  ARRAY['English', 'French', 'Italian'],
  ARRAY['Art', 'Poetry', 'Mystical', 'Creative'],
  ARRAY['/lovable-uploads/3da4a6b0-da99-437a-8673-fcf40dadcace.png'],
  'Art',
  true,
  NULL
),
(
  'Zara',
  'A fashionable avatar perfect for style content and beauty tutorials',
  '/lovable-uploads/7a5cf907-e9a9-4f4f-b32f-a0e2f2697662.png',
  179.99,
  4.6,
  267,
  'FashionStudio',
  'ESFP',
  ARRAY['Stylish', 'Confident', 'Trendy', 'Social'],
  ARRAY['Fashion design', 'Shopping', 'Social media', 'Parties'],
  'Zara grew up in the fashion capital, always ahead of trends. She has an eye for style and loves helping others express themselves through fashion and beauty.',
  'Confident, stylish voice with modern appeal',
  ARRAY['English', 'Spanish', 'Portuguese'],
  ARRAY['Fashion', 'Beauty', 'Social media', 'Lifestyle'],
  ARRAY['/lovable-uploads/7a5cf907-e9a9-4f4f-b32f-a0e2f2697662.png'],
  'Fashion',
  true,
  NULL
),
(
  'Alex',
  'A fitness-focused avatar perfect for workout content and health motivation',
  '/lovable-uploads/620dccd2-1550-40be-95ed-1f20ad2f9b32.png',
  139.99,
  4.7,
  445,
  'FitnessStudio',
  'ESTP',
  ARRAY['Energetic', 'Motivational', 'Athletic', 'Positive'],
  ARRAY['Workout', 'Sports', 'Healthy food', 'Outdoor activities'],
  'Alex discovered the power of fitness early in life and has dedicated themselves to helping others achieve their health goals through motivation and proper training.',
  'Energetic, motivational voice that inspires action',
  ARRAY['English', 'Spanish', 'German'],
  ARRAY['Fitness', 'Health', 'Sports', 'Wellness'],
  ARRAY['/lovable-uploads/620dccd2-1550-40be-95ed-1f20ad2f9b32.png'],
  'Fitness',
  true,
  NULL
),
(
  'Sage',
  'A wise avatar perfect for spiritual content and mindfulness guidance',
  '/lovable-uploads/1fab5331-8802-41ed-b1c5-5d8aab9b3268.png',
  189.99,
  4.9,
  156,
  'WellnessStudio',
  'INFJ',
  ARRAY['Wise', 'Calm', 'Spiritual', 'Insightful'],
  ARRAY['Meditation', 'Philosophy', 'Tea ceremony', 'Ancient wisdom'],
  'Sage has spent years studying ancient wisdom traditions and mindfulness practices. They bring peace and insight to every conversation, helping others find inner balance.',
  'Calm, wise voice with meditative quality',
  ARRAY['English', 'Sanskrit', 'Tibetan'],
  ARRAY['Spirituality', 'Meditation', 'Philosophy', 'Wellness'],
  ARRAY['/lovable-uploads/1fab5331-8802-41ed-b1c5-5d8aab9b3268.png'],
  'Wellness',
  true,
  NULL
);

-- Update TypeScript types to reflect the new schema if needed
COMMENT ON TABLE public.avatars IS 'Updated with marketplace sample data';